name: Adhatama
url: "adhatama.github.io"
permalink: pretty
markdown: kramdown
highlighter: rouge
exclude:
  - package.json
  - node_modules
  - gulpfile.js
# port: 4000
# auto: true
# safe: true
# server: true

